//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageViewerX.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT FILES.
        /// </summary>
        public static string Button_SELECTFILES {
            get {
                return ResourceManager.GetString("Button_SELECTFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT FOLDERS.
        /// </summary>
        public static string Button_SELECTFOLDERS {
            get {
                return ResourceManager.GetString("Button_SELECTFOLDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 Minutes.
        /// </summary>
        public static string Label_10Minutes {
            get {
                return ResourceManager.GetString("Label_10Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 Seconds.
        /// </summary>
        public static string Label_10Second {
            get {
                return ResourceManager.GetString("Label_10Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 Seconds.
        /// </summary>
        public static string Label_15Second {
            get {
                return ResourceManager.GetString("Label_15Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Minute.
        /// </summary>
        public static string Label_1Minute {
            get {
                return ResourceManager.GetString("Label_1Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Second.
        /// </summary>
        public static string Label_1Second {
            get {
                return ResourceManager.GetString("Label_1Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 Seconds.
        /// </summary>
        public static string Label_20Second {
            get {
                return ResourceManager.GetString("Label_20Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Minutes.
        /// </summary>
        public static string Label_2Minutes {
            get {
                return ResourceManager.GetString("Label_2Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Seconds.
        /// </summary>
        public static string Label_2Seconds {
            get {
                return ResourceManager.GetString("Label_2Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 Seconds.
        /// </summary>
        public static string Label_30Second {
            get {
                return ResourceManager.GetString("Label_30Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Minutes.
        /// </summary>
        public static string Label_3Minutes {
            get {
                return ResourceManager.GetString("Label_3Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Seconds.
        /// </summary>
        public static string Label_3Seconds {
            get {
                return ResourceManager.GetString("Label_3Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Seconds.
        /// </summary>
        public static string Label_4Seconds {
            get {
                return ResourceManager.GetString("Label_4Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Minutes.
        /// </summary>
        public static string Label_5Minutes {
            get {
                return ResourceManager.GetString("Label_5Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Seconds.
        /// </summary>
        public static string Label_5Seconds {
            get {
                return ResourceManager.GetString("Label_5Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 Seconds.
        /// </summary>
        public static string Label_6Seconds {
            get {
                return ResourceManager.GetString("Label_6Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 Seconds.
        /// </summary>
        public static string Label_7Seconds {
            get {
                return ResourceManager.GetString("Label_7Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 Seconds.
        /// </summary>
        public static string Label_8Seconds {
            get {
                return ResourceManager.GetString("Label_8Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 Seconds.
        /// </summary>
        public static string Label_9Seconds {
            get {
                return ResourceManager.GetString("Label_9Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Label_About {
            get {
                return ResourceManager.GetString("Label_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossfade.
        /// </summary>
        public static string Label_Crossfade {
            get {
                return ResourceManager.GetString("Label_Crossfade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade In &amp; Out.
        /// </summary>
        public static string Label_FadeInAndOut {
            get {
                return ResourceManager.GetString("Label_FadeInAndOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Location.
        /// </summary>
        public static string Label_FileLocation {
            get {
                return ResourceManager.GetString("Label_FileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string Label_Fullscreen {
            get {
                return ResourceManager.GetString("Label_Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Label_Image {
            get {
                return ResourceManager.GetString("Label_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageList.
        /// </summary>
        public static string Label_ImageList {
            get {
                return ResourceManager.GetString("Label_ImageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Property.
        /// </summary>
        public static string Label_ImageProperty {
            get {
                return ResourceManager.GetString("Label_ImageProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string Label_Interval {
            get {
                return ResourceManager.GetString("Label_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Effect.
        /// </summary>
        public static string Label_NoEffect {
            get {
                return ResourceManager.GetString("Label_NoEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Label_Open {
            get {
                return ResourceManager.GetString("Label_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPI Scaling.
        /// </summary>
        public static string Label_OverrideDPIScaling {
            get {
                return ResourceManager.GetString("Label_OverrideDPIScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Label_Quit {
            get {
                return ResourceManager.GetString("Label_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string Label_Repeat {
            get {
                return ResourceManager.GetString("Label_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Label_SelectFiles {
            get {
                return ResourceManager.GetString("Label_SelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string Label_SelectFolders {
            get {
                return ResourceManager.GetString("Label_SelectFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Label_Show {
            get {
                return ResourceManager.GetString("Label_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In File Manager.
        /// </summary>
        public static string Label_ShowInFileManager {
            get {
                return ResourceManager.GetString("Label_ShowInFileManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        public static string Label_Shuffle {
            get {
                return ResourceManager.GetString("Label_Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Kick In &amp; Out.
        /// </summary>
        public static string Label_SlideKickInAndOut {
            get {
                return ResourceManager.GetString("Label_SlideKickInAndOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slideshow.
        /// </summary>
        public static string Label_Slideshow {
            get {
                return ResourceManager.GetString("Label_Slideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Label_SlideshowStart {
            get {
                return ResourceManager.GetString("Label_SlideshowStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Label_SlideshowStop {
            get {
                return ResourceManager.GetString("Label_SlideshowStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch In.
        /// </summary>
        public static string Label_StretchIn {
            get {
                return ResourceManager.GetString("Label_StretchIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch Out.
        /// </summary>
        public static string Label_StretchOut {
            get {
                return ResourceManager.GetString("Label_StretchOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Top.
        /// </summary>
        public static string Label_TopMost {
            get {
                return ResourceManager.GetString("Label_TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects.
        /// </summary>
        public static string Label_TransitionEffect {
            get {
                return ResourceManager.GetString("Label_TransitionEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Label_View {
            get {
                return ResourceManager.GetString("Label_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPI Scaling ({0}%).
        /// </summary>
        public static string String_OverrideDPIScaling {
            get {
                return ResourceManager.GetString("String_OverrideDPIScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPI Scaling (100%).
        /// </summary>
        public static string String_OverrideDPIScaling_Default {
            get {
                return ResourceManager.GetString("String_OverrideDPIScaling_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag &amp; Drop.
        /// </summary>
        public static string String_Welcome_DragAndDrop {
            get {
                return ResourceManager.GetString("String_Welcome_DragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your image files or folder here.
        /// </summary>
        public static string String_Welcome_YourImageHere {
            get {
                return ResourceManager.GetString("String_Welcome_YourImageHere", resourceCulture);
            }
        }
    }
}
